### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by mpdehnel** [lordqwerty/TamarinAssist#1]
I can't quite work out how to do this (or I would have submitted a PR), but is it possible to include functionality such that when you hit Cmd+/ (or Edit->Comment->Toggle Comment) that it comments out the line you're on? 

This is normal behaviour for all other languages.

Thanks!

Martin

**Comment by lordqwerty** [comment]
Hi Martin,

Thanks for the comment been meaning to do this for a while but did not get around to it. I have now added basic ability for block / inline comments. See commit https://github.com/lordqwerty/TamarinAssist/commit/4090583364a0e8479bfe35af284eb0f47eab26d4 .

The [spthy.sublime-syntax](https://github.com/lordqwerty/TamarinAssist/blob/master/Syntaxes/spthy.sublime-syntax) file needs some work and the [Comments.tmPreferences](https://github.com/lordqwerty/TamarinAssist/blob/master/Preferences/Comments.tmPreferences) also needs fine tuning. 

Any contributions would be gladly accepted and appreciated. 

Best,

Jorden

**Comment by mpdehnel** [comment]
Excellent -- thank you, this is perfect!
