### ISSUE TITLE
`axiom` has been renamed `restriction` in the develop branch of Tamarin

### ISSUE THREAD

**Issue by mpdehnel** [lordqwerty/TamarinAssist#3]
Could you add `restriction` as a keyword, similar to `axiom`? `axiom` is deprecated in recent versions of Tamarin.

:-)

**Comment by lordqwerty** [comment]
This has now been done in commit https://github.com/lordqwerty/TamarinAssist/commit/3df65720f17ebdfc00ad4661d06f7463897f13d8
